const quotes = [
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { text: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle" },
  { text: "You don't have to be positive all the time. It's perfectly okay to feel sad, angry, annoyed, frustrated, scared, or anxious. Having feelings doesn't make you weak, it makes you human.", author: "Lori Deschene" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "You are not your worst moments. You are not your pain. You are the person who survived them.", author: "Unknown" },
  { text: "It's okay to not be okay, as long as you don't give up.", author: "Karen Salmansohn" },
  { text: "Healing is not linear. Be patient with yourself.", author: "Unknown" },
  { text: "You have survived 100% of your worst days. You're doing great.", author: "Unknown" },
  { text: "Stars can't shine without darkness.", author: "D.H. Sidebottom" },
  { text: "Be gentle with yourself. You're doing the best you can.", author: "Unknown" },
  { text: "Your current situation is not your final destination. The best is yet to come.", author: "Unknown" },
  { text: "One small crack does not mean that you are broken, it means that you were put to the test and you didn't fall apart.", author: "Linda Poindexter" },
  { text: "Sometimes the bravest thing you can do is ask for help.", author: "Unknown" },
  { text: "Recovery is not a race. You don't have to feel guilty if it takes you longer than you thought it would.", author: "Unknown" },
  { text: "You are allowed to be both a masterpiece and a work in progress simultaneously.", author: "Sophia Bush" },
  { text: "Just because no one else can heal or do your inner work for you doesn't mean you can, should, or need to do it alone.", author: "Lisa Olivera" },
  { text: "There is hope, even when your brain tells you there isn't.", author: "John Green" },
  { text: "Your struggle is part of your story, not the end of it.", author: "Unknown" },
  { text: "Take it one day at a time. One hour, if you need to. One minute. Whatever gets you through.", author: "Unknown" },
  { text: "You are worthy of love and care — especially from yourself.", author: "Unknown" },
  { text: "The fact that you're still here means you're strong enough to keep going.", author: "Unknown" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "You don't have to control your thoughts. You just have to stop letting them control you.", author: "Dan Millman" },
  { text: "Nothing is permanent in this wicked world, not even our troubles.", author: "Charlie Chaplin" },
  { text: "Even the darkest night will end, and the sun will rise.", author: "Victor Hugo" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "You are enough, just as you are.", author: "Meghan Markle" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The darkest hour has only sixty minutes.", author: "Morris Mandel" },
  { text: "This too shall pass.", author: "Persian Proverb" },
  { text: "You are stronger than you think.", author: "Unknown" },
  { text: "Breathe. You're going to be okay.", author: "Unknown" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "Your feelings are valid. All of them.", author: "Unknown" },
  { text: "You matter more than you know.", author: "Unknown" },
  { text: "Asking for help is a sign of strength, not weakness.", author: "Unknown" },
  { text: "It's okay to have a bad day. Tomorrow is a new beginning.", author: "Unknown" },
  { text: "Scars remind us where we've been. They don't have to dictate where we're going.", author: "David Rossi" },
  { text: "You are not alone in this. So many others have felt what you feel.", author: "Unknown" },
  { text: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
  { text: "You don't have to be perfect to be worthy of love.", author: "Unknown" },
  { text: "Sometimes surviving is the bravest thing you can do.", author: "Unknown" },
  { text: "Your past does not define your future.", author: "Unknown" },
  { text: "You are loved more than you will ever know.", author: "Unknown" },
  { text: "The bravest thing I ever did was continuing my life when I wanted to die.", author: "Juliette Lewis" },
  { text: "Even on your darkest day, you are still worthy of kindness.", author: "Unknown" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Unknown" },
  { text: "You are not a burden. You are a human being who is struggling, and that is okay.", author: "Unknown" },
  { text: "Your life has value and purpose, even if you can't see it right now.", author: "Unknown" },
  { text: "Pain is real. But so is hope.", author: "Unknown" },
  { text: "Just keep breathing. One breath at a time.", author: "Unknown" },
  { text: "You deserve to take up space in this world.", author: "Unknown" },
  { text: "Healing begins the moment you choose yourself.", author: "Unknown" },
  { text: "It's okay to rest. Rest is not giving up.", author: "Unknown" },
  { text: "The sun will rise and we will try again.", author: "Twenty One Pilots" },
  { text: "You are more than your darkest thoughts.", author: "Unknown" },
  { text: "Even on the hardest days, small steps forward still count.", author: "Unknown" },
  { text: "Be proud of yourself for how far you've come.", author: "Unknown" },
  { text: "What you are going through is temporary. You are not.", author: "Unknown" },
  { text: "You survived yesterday. You can survive today.", author: "Unknown" },
  { text: "Your story isn't over yet.", author: "Unknown" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "You are worthy of healing.", author: "Unknown" },
  { text: "The only way out is through.", author: "Robert Frost" },
  { text: "You've come too far to give up now.", author: "Unknown" },
  { text: "Give yourself the same compassion you'd give a good friend.", author: "Unknown" },
  { text: "Somewhere, someone cares about you more than you know.", author: "Unknown" },
  { text: "Every storm runs out of rain.", author: "Maya Angelou" },
  { text: "There are better days coming. Hold on.", author: "Unknown" },
  { text: "You are not weak for struggling. You are human.", author: "Unknown" },
  { text: "Courage doesn't always roar. Sometimes it's the quiet voice that says 'I'll try again tomorrow.'", author: "Mary Anne Radmacher" },
  { text: "It's okay if all you did today was survive.", author: "Unknown" },
  { text: "You are not defined by your lowest moments.", author: "Unknown" },
  { text: "Your feelings will not last forever, even when it feels like they will.", author: "Unknown" },
  { text: "You are a work in progress. That is a beautiful thing.", author: "Unknown" },
  { text: "Even small acts of self-care matter.", author: "Unknown" },
  { text: "Be patient. Good things take time. So does healing.", author: "Unknown" },
  { text: "You are worth fighting for — especially by yourself.", author: "Unknown" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "One day at a time. One breath at a time. One step at a time.", author: "Unknown" },
  { text: "Storms don't last forever.", author: "Unknown" },
  { text: "Healing looks different for everyone. Your journey is valid.", author: "Unknown" },
  { text: "You have made it through every hard day so far. This one is no different.", author: "Unknown" },
  { text: "It's okay to feel broken sometimes. Broken things can be rebuilt.", author: "Unknown" },
  { text: "You owe it to yourself to keep going.", author: "Unknown" },
  { text: "Every sunrise is a new chance.", author: "Unknown" },
  { text: "You are not too much. You are not too little. You are just right.", author: "Unknown" },
  { text: "Your pain is valid. Your healing is valid. You are valid.", author: "Unknown" },
  { text: "Be kind to yourself. You're learning.", author: "Unknown" },
  { text: "The most important thing you can do today is take care of yourself.", author: "Unknown" },
  { text: "If you're reading this, you made it through yesterday. That matters.", author: "Unknown" },
  { text: "Growth is painful. Change is painful. But nothing is as painful as staying where you don't belong.", author: "Mandy Hale" },
  { text: "You can do this. Even if 'this' just means getting through the next hour.", author: "Unknown" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Sometimes the smallest step in the right direction ends up being the biggest step of your life.", author: "Unknown" },
  { text: "Your worth is not measured in productivity.", author: "Unknown" },
  { text: "You deserve rest. You deserve peace. You deserve to heal.", author: "Unknown" },
  { text: "Life doesn't get easier. You get stronger.", author: "Unknown" },
  { text: "It's okay to not have it all together.", author: "Unknown" },
  { text: "What you resist persists. What you accept transforms.", author: "Carl Jung" },
  { text: "Be the person you needed when you were younger.", author: "Unknown" },
  { text: "You are allowed to outgrow things that no longer serve you.", author: "Unknown" },
  { text: "The hardest step is usually the first one.", author: "Unknown" },
  { text: "Vulnerability is not weakness. It takes courage to let people see your truth.", author: "Brené Brown" },
  { text: "You are allowed to start over.", author: "Unknown" },
  { text: "Feelings are visitors. Let them come and go.", author: "Mooji" },
  { text: "There is no timestamp on trauma.", author: "Unknown" },
  { text: "You will get through this, even if you don't believe it right now.", author: "Unknown" },
  { text: "I am not what happened to me. I am what I choose to become.", author: "Carl Jung" },
  { text: "We are all a little broken. But last time I checked, broken crayons still color.", author: "Unknown" },
  { text: "You deserve to be here.", author: "Unknown" },
  { text: "Sometimes the most productive thing you can do is rest.", author: "Unknown" },
  { text: "Not every day has to be a good day. Some days just have to be survived.", author: "Unknown" },
  { text: "Your story deserves to be told. And it isn't finished yet.", author: "Unknown" },
  { text: "You are the author of your life. The next chapter can be different.", author: "Unknown" },
  { text: "Somewhere on this planet, someone needed to hear your voice today.", author: "Unknown" },
  { text: "You are someone's reason to smile.", author: "Unknown" },
  { text: "The most powerful thing you can do right now is choose to still be here.", author: "Unknown" },
  { text: "You are not invisible. You matter.", author: "Unknown" },
  { text: "Don't give up on the person you're becoming.", author: "Unknown" },
  { text: "When you can't find the sunshine, be the sunshine.", author: "Unknown" },
  { text: "Every day you wake up is a new chance to start again.", author: "Unknown" },
  { text: "You are important to someone, even when it doesn't feel that way.", author: "Unknown" },
  { text: "It's okay to take the long way. You'll still get there.", author: "Unknown" },
  { text: "The past cannot be changed. But the future is still unwritten.", author: "Unknown" },
  { text: "You are not alone. You have never been alone.", author: "Unknown" },
  { text: "Hard days build strong people.", author: "Unknown" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "The things that make you different are the things that make you great.", author: "Unknown" },
  { text: "You don't have to earn rest. You don't have to earn care.", author: "Unknown" },
  { text: "Speak to yourself like someone you love.", author: "Unknown" },
  { text: "You are more resilient than you realize.", author: "Unknown" },
  { text: "Emotions are information, not commands.", author: "Unknown" },
  { text: "What you feel is not forever, even when it feels that way.", author: "Unknown" },
  { text: "Your sensitivity is a gift, not a flaw.", author: "Unknown" },
  { text: "Healing is messy and nonlinear and that is perfectly okay.", author: "Unknown" },
  { text: "You don't have to have it figured out to move forward.", author: "Unknown" },
  { text: "Even broken things can be beautiful.", author: "Unknown" },
  { text: "Small steps still move you forward.", author: "Unknown" },
  { text: "Out of suffering have emerged the strongest souls.", author: "Khalil Gibran" },
  { text: "Be here. This moment needs you.", author: "Unknown" },
  { text: "You are allowed to cry. You are allowed to feel everything.", author: "Unknown" },
  { text: "Behind every smile there may be pain no one knows about. Be kind, always.", author: "Unknown" },
  { text: "You were given this life because you are strong enough to live it.", author: "Unknown" },
  { text: "In the end, we only regret the chances we didn't take.", author: "Lewis Carroll" },
  { text: "When it rains, look for rainbows. When it's dark, look for stars.", author: "Unknown" },
  { text: "You are doing better than you think you are.", author: "Unknown" },
  { text: "There is no shame in needing help. Even trees need rain.", author: "Unknown" },
  { text: "You have permission to take up space, feel deeply, and ask for more.", author: "Unknown" },
  { text: "Your mind may lie to you. It does not mean you have to believe it.", author: "Unknown" },
  { text: "Hold on. Things can change faster than you think.", author: "Unknown" },
  { text: "You are braver today than you were yesterday.", author: "Unknown" },
  { text: "Nothing about you is too broken to be loved.", author: "Unknown" },
  { text: "You have survived things that were supposed to break you.", author: "Unknown" },
  { text: "The world is better with you in it.", author: "Unknown" },
  { text: "Let your tears water the seeds of your future happiness.", author: "Steve Maraboli" },
  { text: "A bad day does not equal a bad life.", author: "Unknown" },
  { text: "You can feel lost and still be on the right path.", author: "Unknown" },
  { text: "There is strength in softness.", author: "Unknown" },
  { text: "You don't have to perform wellness to deserve care.", author: "Unknown" },
  { text: "Your feelings deserve to be heard — especially by you.", author: "Unknown" },
  { text: "It's okay if your healing journey is slow. Slow is still moving.", author: "Unknown" },
  { text: "The capacity for hope is the most significant fact of life.", author: "Norman Cousins" },
  { text: "You survived every bad day you ever had. Your success rate is 100%.", author: "Unknown" },
  { text: "When you feel like giving up, remember why you held on for so long.", author: "Unknown" },
  { text: "Everything you've been through has made you who you are.", author: "Unknown" },
  { text: "Breathe in courage. Breathe out fear.", author: "Unknown" },
  { text: "Some days, just showing up is enough.", author: "Unknown" },
  { text: "You have an entire lifetime ahead. This pain is not the whole story.", author: "Unknown" },
  { text: "It's brave to feel, even when feeling hurts.", author: "Unknown" },
  { text: "Give yourself permission to heal.", author: "Unknown" },
  { text: "What feels impossible today might feel manageable tomorrow.", author: "Unknown" },
  { text: "You are real. Your pain is real. Your hope is real too.", author: "Unknown" },
  { text: "Life is tough, my darling, but so are you.", author: "Stephanie Bennett-Henry" },
  { text: "You're allowed to have a messy, imperfect, human experience.", author: "Unknown" },
  { text: "There is always a light — sometimes you just need someone to help you find it.", author: "Unknown" },
  { text: "Your emotions are not your enemy.", author: "Unknown" },
  { text: "You matter — to this world, to someone, always.", author: "Unknown" },
  { text: "Even in darkness, life is still worth living.", author: "Unknown" },
  { text: "The most radical act of self-care is staying.", author: "Unknown" },
  { text: "Surviving hard days is an act of courage.", author: "Unknown" },
  { text: "Rest when you need to. Cry when you need to. Then keep going.", author: "Unknown" },
  { text: "You are not meant to be small. You are meant to be whole.", author: "Unknown" },
  { text: "Your heart is still beating. That means there's still time.", author: "Unknown" },
  { text: "You are allowed to want better for yourself.", author: "Unknown" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "The rain will stop. The night will end. The hurt will fade.", author: "Unknown" },
  { text: "You are not too broken to be fixed. You are human.", author: "Unknown" },
  { text: "Keep going. The person you're becoming is worth it.", author: "Unknown" },
  { text: "Sometimes all you can do is not give up. And that's enough.", author: "Unknown" },
  { text: "You are still growing. Give yourself time.", author: "Unknown" },
  { text: "You deserve the effort it takes to keep yourself safe.", author: "Unknown" },
  { text: "Let yourself be held by the people who love you.", author: "Unknown" },
  { text: "Your presence in this world is not an accident.", author: "Unknown" },
  { text: "Every version of you has made it through so far.", author: "Unknown" },
  { text: "You are someone's reason to be thankful.", author: "Unknown" },
  { text: "You've weathered storms before. You can weather this one too.", author: "Unknown" },
  { text: "Even now, in your pain, you are still enough.", author: "Unknown" },
  { text: "The next chapter of your life hasn't been written yet.", author: "Unknown" },
  { text: "You are not a mistake. You were made with purpose.", author: "Unknown" },
  { text: "Your existence changes the world, even when you can't see how.", author: "Unknown" },
  { text: "Healing is possible. Recovery is possible. A better day is possible.", author: "Unknown" },
  { text: "On the other side of your biggest fear is your greatest freedom.", author: "Unknown" },
  { text: "You didn't come this far to only come this far.", author: "Unknown" },
  { text: "What you're going through is real. What you feel is real. And you can get through it.", author: "Unknown" },
  { text: "When everything feels heavy, just focus on the next breath.", author: "Unknown" },
  { text: "You are not your diagnosis. You are not your history. You are you.", author: "Unknown" },
  { text: "There will be a day when this pain becomes your superpower.", author: "Unknown" },
  { text: "It gets better. And if it isn't better yet, it isn't over yet.", author: "Unknown" },
];

export function getRandomQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

export default quotes;